services:
  api:
    build: .
    container_name: pixelfort-api
    ports:
      - "9000:8000"
    volumes:
      - ./api:/app/api
      - ./storage:/app/storage
      - ./tests:/app/tests
      - ./static:/app/static
    env_file:
      - .env
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload